---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCohSrWWKgMmlIBLTbNZ8X7Ttz+Pm4dZbvQ+oeslwj+AuxfJ1RJYI4aHqZ2WBXYZhcbkqV6W+9/XkFnmrS8knCm/oumMT3f20+sC4InIeG7BFVVIwnPJ2XnwlS2McP1jGQpzcOaQtKNYw6PEWPXmFt74+VbJa7fX0Up4fV2kFfggNNaTxTyyUO2KbKI602VqnTlRIMnLUx8V0qUV7Jkc7u/FEAW6kXTaQ9irn9jFpWilEb0cXUlF1VSBnIgrbRmJJ1d0igQPP6fwvCyyFtVrMwp8Gu6RfapBwtHb/OlB9DsWqGl0AbDuhV7LqbXAy6Tx6BWCiSzNY9wTdlSm6Lcb95VJSrO/bwdCAQqozQ4TfbJsJOhd7PS4cCkjH2hmOf5mifzB6O4dmXoJeoNi6vYUX8DYAszGMDh3hNfrxDqL+CwQf9RudSSYOoCsjuLslslIEDk2BjLA9FGnx+jjrJfp/McFfvYneK67SHKhj2TL2LAv4rSOMXz0bC20GSzSnPpQvU0E/MyDYYpsd0lHF1MBTglXwUxrTRUH/sKh2NVSoCAB3IFXCbHgV4IeXd4HGpWuGiXeG15A6WRbiVtOi84YT4R/NPx5nsdKRqTgkno4giXuBuiKDC2zwMdvCXTjl8D7WbtYZ1oU1QaPpYSb0sO3i5i3UhjlELQlY8WI8BpuCy8HXrw8r3SX6d6ANg5uWE1/lRyvJ/e0sbS1jtv2fjDE5LrJHYTLNQwPpQeIg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
    type: Opaque
