---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAql25sc6y4MBgqT0furOzv1LtW1slat5NYBsKpt0Pz9r7SZYOmzpLXexP1c6P0t4xcAdoWvKJ6Yj4jgxznrQ8wOoxL3/ee24CFQLBs8keWgRE8vg6ZyLLQtXAitz+4aPi+b1CHylWr7yn3RtJs+mSV8SG4u1z3GbKFDLioNScSBpTJj6t/2vNUJqxjvLINche7aufXaPdMFcoh92oneANwSbQ1sPAiBt7za8l7/QMzr4sY+T8sqPHjjvj/idvuJHhjp3vXgETUGYZMJinTVmwebTYrNkTRdAy+00oLKjo6Ub5fwCAy44vMECRuqQHwYChWn2vTWlVNdEMtjowSW4c0ebVI5iScP84c5T9zQpC5p5sdZF7Q3zrc88Wv6W0s9dcVfJ+sbZnvV+MU+e2yJCuZ9dVWKH03e5sODTg+nKNsdNyCSV5dvmwdQaCreJ3f24cJaMU5epKM8Cr0NgKRLlQU1Qo1eaqaZkDs5dRx36JHToZxv0XaKZRXiPhw3FkIBvkhq5x8gZdc/zB6pAFE3JAbKU+afESzVZLCBu620qISeE/dYT7Q3fozwzBKn1S9zkDdh9zV+/Z2RyX94AVVOv6vSiCcpI0UIj3SdueMwVoSLgYLJDtXeT6XhN2OlWJ9l3R98e0Mcup9VT2ro0SjUQBNP8mHmTMkQZvhrAKIYjc9Auo4V/0I+zemO4Zw7saLcqw+DsgNYxUK89/eojLHCw17OiRxuTtMee1MDDqEI+PdUA==
    admin-user: AgCtMkc5XWX9+EJ36Jkm67UznPBN9/DIDGGbxIFIUZ+h3AFd8OiR/tJ1Y7+qtawSnoPyvRqgBJ8f5Iv54EpBOKAJ+N3fsCS2nWGh7wQ+7+dSE6FOPslQn4I8MG2AnSgjhbsZQz3QvaC1xhn9tcjcLmDuBO6UcY5KCMk2fDMDYDEI378moN3YSdMf2i/TqhL31tHyEATE3SQvwFc5Bft00myKx1lXlFByi46cQ26lsnO50rYCEoA1zUxDyNfZ302GfnO+yjAtK38RD0EwV60WVTQvRsMNcC6KVpnYy+nldMaGxWtJDj26JAgDlKThsPr3b0b3wJIqFbeVH4P0a51zO4IIdtLNXIXSypOA5FCWXpg8S7JfIqBCSbteC+92Sohi5XY0+NdxgRT88r/UGnUAn5oAmbTpUGZniulwicEKTbYKAnZotmx1+piN+sR+K9jJ1JLM230jhFZUggQdDhMJFZlhbwokimliTChNZZzLfGuXqgXyYHZgLt93KCjOlnNu5I9zzSWpVjlm4Jt5y9eBRwNcMigr8dOUJvbtGLE172xTWPNTfzS3oPTICMVCDqdLr4J9L+0ojRzCCar45cc5fU/E56UAkm2lUg/3QVGCSX0i7epkBetUSQt4rTc6A/5+U72+u0l1tn3gG+0ga9nytzpVY2IDCtopbFYeM3TJa1LiHXmhyQ+RRlmf5omL6uflhv3AloxMew==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
    type: Opaque
