---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAH9avus14OHmq55ugFWl7O/A0ENKCzhBOvFrHEPqyEuycdGA/hhhWN0zbFo7DLc1kBXm+UnYFXKDVcrflBo7NrFS9sWfrRruSDrR65dsdky1YB8XyLGRqTj95qrZX/7ZFWI3LYF+vftAR7Nj7u/nRjq3eYjzRXaHWmzRE2SHqF5NbqmCCWk93VyNfW5G0oP492HOca34Nhb16S9p0S62q4V4Qq0oa6ABkMx+6EwT7EVZd20cmhXCZ3qpi92aAmgz0GVi2upR41VZAvymOMkhhPO21IiIPBBOXufeXtMuSR1Y9fs+Y+LyPRIup4neyPl2sImBBQpM8t4yMbPK89IQCFuCfjW2xxsZk+VH3S1TWtNT2e+Cfo53Cw8ap/x0Quh8EMLAAUIxD4w17vQxJ1mxND/tz6yEbEkC8AqpwfcQ089QXrR6TdUhSMCzdJKeFKac/dZ4CDqyeKD3sOemkhw+EmPhhKeX9wwkKzjB+weszinvM65iJX6S+px09kIOll26a993BPnMbU2JP8KlbhWZGHxABLJDFH6a+i6geVAOMkC9Q2HNn4FcqAYCxiX6/OjSTCzAPWvMut4K7mRzaptHHLB8dbx+ztw+yiunjgCot7fo37wwh/aSoDAIC4+4vz1WXcBxlnGkQia46bRVtOBBVz7CsEzOdiuXG/MorjgFD3azUN4chNupz9iCQ8bEP0C/a2IfkYZm1OpMZJqI3OD+9S/7NZSFJ10cXh2zWFyhmJNQ==
    admin-user: AgBb4/awdxXcOmfGB6RG6lg9PxtXFJTvArTh5arDdaY0gjpXPsVl3M+bkQFI8SadVKO8xfp8forVc7KYLx9tJ/VNLw+pXUSm71buYY5RDYNUQnAqI28KUeUTNADElirG4a33eSb/TXiImAJmcZw29J0cxjiBx9xvT3W3qzeghiBaHe+vxeHXFsCz3WnX126Y7gZZ5zMV9b7iqq4/AhdMzikbDw461KgczEj/lZwHf5TbLh691li4TS9ibjdT2C0AxmIvpQjXgl/DDeg8cILE5v6WJhofw7QwNfosGxmR2hjJDcmubbEV83HUoXsGbdEu5MQRnhj1qXdQnrxzWRPCnttnbF52ym/madzR2fLrWExjUerlSUtW4OBenpdAoxncbDQG9fGbtswUgZAaKdYmtVlFf8GrOSJn4jXNrRW/bQU5oyq/q20oqrpFFX2pDxu8PuWf9Dzr7y7SOL1m0+OQMBjEWrpOOr6hXAUUp9V4qqecsYSWOrZ9KtR5x0t6TFB1GubXeIFbn8MmS5lIIllICZTQ1XlSLt6/pxInRt9uz/TFN33cQqp4UOGVb78c4Q6MM1Xt3JtDqWYZzlLEZbM5E96iceRXYxCoStQXgDJNLXrcZSuyYnRodPMNchTqE2KJ9FIYpdfSqZwH1cLc+IKA5j1SBO3T7ZRZeI3Ha2HggmQLUwjdRLDCyq4ySP767ee9FCYHFFQEOg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
    type: Opaque
