---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-smb-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: prometheus-smb-pv
  storageClassName: smb