grafana: # deployed with prometheus
  enabled: false

loki:
  config:
    server:
      log_level: debug
  persistence:
    enabled: true
    storageClassName: monitoring-smb
    size: 200Gi

promtail:
  enabled: true
  rbac:
    create: true
  podMonitor:
    enabled: false