---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: four-hour-snapshot
  namespace: longhorn-system
spec:
  cron: "0 */4 * * *"
  groups:
  - default
  - longhorn-snapshots
  retain: 12
  concurrency: 2
---
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"
  groups:
  - longhorn-daily
  retain: 90
  concurrency: 1
---
kind: RecurringJob
metadata:
  name: weekly-backup
  namespace: longhorn-system
spec:
  cron: "0 3 * * 0"
  groups:
  - longhorn-weekly
  retain: 12
  concurrency: 1