---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: volume-four-hour-snapshot
  namespace: longhorn-system
spec:
  name: volume-four-hour-snapshot
  cron: "0 */4 * * *"
  task: "snapshot"
  groups:
  - longhorn-snapshots
  retain: 12
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: volume-daily-backup
  namespace: longhorn-system
spec:
  name: volume-daily-backup
  cron: "0 2 * * *"
  task: "backup"
  groups:
  - longhorn-daily-backup
  retain: 90
  concurrency: 1
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: volume-weekly-backup
  namespace: longhorn-system
spec:
  name: volume-weekly-backup
  cron: "0 4 * * 0"
  task: "backup"
  groups:
  - longhorn-weekly-backup
  retain: 12
  concurrency: 1