kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-weekly-backup
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  recurringJobSelector: '[
    {
      "name":"longhorn-snapshots",
      "isGroup":true
    },
    {
      "name":"longhorn-weekly-backup",
      "isGroup":true
    }
  ]'
