stages:
  - CI
  - CD

pre-ci:
  stage: CI
  variables:
    FF_USE_ATTACH_STRATEGY: "false"
  script:
    - echo "Checking changes..."

opentofu-ci:
  stage: CI
  rules:
    - changes:
        - infrastructure/**/*
        - pipelines/gitlab/opentofu-ci.yml
        - pipelines/gitlab/opentofu-cd.yml
  trigger:
    include: pipelines/gitlab/opentofu-ci.yml
    strategy: depend

opentofu-cd:
  stage: CD
  needs: ["opentofu-ci"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - infrastructure/**/*
        - pipelines/gitlab/opentofu-cd.yml
  trigger:
    include: pipelines/gitlab/opentofu-cd.yml
    strategy: depend

homeassistant-ci:
  stage: CI
  rules:
    - changes:
        - applications/homeassistant/**/*
        - pipelines/gitlab/homeassistant-ci.yml
        - pipelines/gitlab/homeassistant-cd.yml
  trigger:
    include: pipelines/gitlab/homeassistant-ci.yml
    strategy: depend

homeassistant-cd:
  stage: CD
  needs: ["homeassistant-ci"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - applications/homeassistant/**/*
        - pipelines/gitlab/homeassistant-cd.yml
  trigger:
    include: pipelines/gitlab/homeassistant-cd.yml
    strategy: depend

k8s-ci:
  stage: CI
  variables:
    FF_USE_ATTACH_STRATEGY: "false"
  rules:
    - changes:
      - argocd/**/*
      - applications/kubernetes/**/*
  script:
    - echo "K8s CI TBD..."

nixos-ci:
  stage: CI
  variables:
    FF_USE_ATTACH_STRATEGY: "false"
  rules:
    - changes:
      - nixos/**/*
  script:
    - echo "NixOs CI TBD..."