---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCddk4ZsXZsPbuTS0kOVjs5LqXWCP+FEmy+pRbabiUvvkCs087JBz8A/BBClPMndVOxPpxXz4IDM+6HHSrn0Zn214JDtoNVTRyyJR1GmYuXt4lcfSGI6kOkfT6yHWkctmtVayyI2l6wNMoFs1Uv1gZnoHYq0kz4bxMENp1RH4xEdRegAjD3lJ0ykNBoYVvGnkjOG06GbJLsUplk4Wmu9V7Y3OJ5+2uxMOd98zk1aOejqS3urtZf8HNSoCAH7GVr+xFLPJzH6fXGOryvlivazNUjU+SSLV+4hesYqyGujAs87lxCEixuJgxqkjG1TMhaAoB1RGkeYdyeHeyIHE1OMXywaUrTo7nU1EUQog+lqZe9Z9dCsLnlHR8Ka8Di1NGhsCYEuHvyc1v427t4EZltqdtua7nR7lmId+oUKMgIN3MniTPkOUSCh8vq3wnfwdiQwW09/J1HQOzOqTTSdo4ZAostlU77uyYirwfwpUG3tqG9wLfIHtcLDAG/ZPYvpjnwgZ2nGvmld7oMeO9l1amU5H6oIq3I0EwafC5cS/OnlLMlVIAr0NAl6Jc72ZByvF6zQ5C730afgNv4wWKwFnBtw7WtTiKB0adcLExSZkR2SWIuE0Wk0B+Rb1fh1+Qzf+bWkCDzCOsulIc6Yzj3tTuKkNO4LyWA9oOJV3QFrt+1c2VwqvV4fqqoLPYY0r+luYITdcA7llEHOMWVxHbxmcjaAcw7tkTFKWKKHaIbsiAx9JmmkZbHFdTxnzjL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
