configuration:
  kestra:
    variables:
      globals:
        github-repo: https://github.com/LucaEggenberg/homelab

extraEnv:
  - name: SECRET_ANSIBLE_SSH_KEY
    valueFrom:
      secretKeyRef: 
        key: ANSIBLE_SSH_KEY
        name: ansible-ssh-secret

dind:
  image:
    tag: dind
  args:
    - --log-level=fatal
  securityContext:
    runAsUser: 0
    runAsGroup: 0
securityContext:
  runAsUser: 0
  runAsGroup: 0
