configuration:
  kestra:
    variables:
      globals:
        github-repo: https://github.com/LucaEggenberg/homelab

common:
  extraEnvFrom:
    - secretRef:
        name: tofu-secrets

dind:
  image:
    tag: dind
  args:
    - --log-level=fatal
  securityContext:
    runAsUser: 0
    runAsGroup: 0
securityContext:
  runAsUser: 0
  runAsGroup: 0
