apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kestra-ingressroute
  namespace: kestra
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`kestra.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: kestra-service
      port: 8080
  tls:
    secretName: kestra-certificate-secret