apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
      - image: jellyfin/jellyfin
        imagePullPolicy: Always
        name: jellyfin
        ports:
        - containerPort: 8096
          name: web
          protocol: TCP
        env:
        - name: TZ
          value: Europe/Zurich
        volumeMounts:
        - mountPath: '/config'
          readonly: false
          name: smb
          subPath: config
        - mountPath: '/movies'
          readonly: false
          name: smb
          subPath: movies
        - mountPath: '/shows'
          readonly: false
          name: smb
          subPath: shows
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: jellyfin-smb-pvc

        