
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-ingressroute-certificate
  namespace: media
spec:
  secretName: qbittorrent-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - qbittorrent.kube.eggenberg.io