apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  selector: 
    matchLabels:
      app: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - image: lscr.io/linuxserver/qbittorrent:latest
        name: qbittorrent
        ports:
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
          - mountPath: /config
            name: arrstack
          - mountPath: /media
            name: smb
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: jellyfin-smb-pvc
        - name: arrstack
          persistentVolumeClaim:
            claimName: qbittorrent-pvc
      restartPolicy: Always