apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  selector: 
    matchLabels:
      app: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - image: lscr.io/linuxserver/qbittorrent:latest
        name: qbittorrent
        ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          - containerPort: 6881
            name: web-tcp
            protocol: TCP
          - containerPort: 6881
            name: web-udp
            protocol: UDP
        volumeMounts:
          - mountPath: /config
            name: arrstack
          - mountPath: /media
            name: smb
        
      - image: qmcgaw/gluetun
        name: gluetun
        env:
          - name: VPN_SERVICE_PROVIDER
            value: protonvpn
          - name: VPN_TYPE
            value: wireguard
          - name: WIREGUARD_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: WIREGUARD_PRIVATE_KEY
                name: proton-secrets
          - name: VPN_PORT_FORWARDING
            value: on
          - name: VPN_PORT_FORWARDING_PROVIDER
            value: protonvpn
        volumeMounts:
          - name: tun
            mountPath: /dev/net/tun
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true

      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: jellyfin-smb-pvc
        - name: arrstack
          persistentVolumeClaim:
            claimName: qbittorrent-pvc
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
      restartPolicy: Always