apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media 
spec:
  ports:
  - name: web
    port: 8080
  - name: web-tcp
    port: 6881
    protocol: TCP
    targetPort: 6881
  - name: web-udp
    port: 6881
    protocol: UDP
    targetPort: 6881
  selector:
    app: qbittorrent