apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-ingressroute-certificate
  namespace: minio-system
spec:
  secretName: minio-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - api.minio.kube.eggenberg.io
  - ui.minio.kube.eggenberg.io