---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: minio-system
spec:
  encryptedData:
    rootPassword: AgBeTZJNWr1rzdHa/jeeE+XbEYasvElFVlCri5NWHwGIF5dA8XIM8SfUQu5SD2xzLD6YUYPPjz8gT2kPFt1fclM84B0fzAnczpKkVJBVEpebmbsXAqt65E2o6Ns5iS9JcBov5Gq0sRzPeYytx6JJGy7f4E0UBU8HB9+t9wsLI7YV4F0NFNEjUlnun9C106P+eBhmobcN8zA0hud4RQRxnkMUgKFPEVZLftjG5Bc4JHTtpKkzhNgPjgOFcJx5HIsgie0znhK3dE9Dvh2Vbot8feFxIBoaXwktXHHjDNndhMbK9Nmy0sV+dbdgH9Ial9fCCQyFGCwbzd0L6clVuS5R1iPmQ9yFQteV/qFkHk5nPujC0eIjaa87+PcXtHMEN8jg1EvUTzVx8FsCTkMYP9+w0TUKrrTdlDKNb2maLi7RPu9XYgOJe+7d2CVQzgWGWFEyicFbBiVts/lDdKVxvTrn1tj65faQNi5KCAP/rF0fqlwpo8lhOQs5b1P44YS6xEQpLJx8dUIIjBjAW1FHL8ypyNnSjwwD7Y66gT9SB5DDxKhPcusCHSQVf9ShYUqxJ7X13ZVhufm7r4ojvF0x8bUgCR5zBY30/bMLVzRqGlCTEmqdwg0etJI9fQpJzriLj38yg8kONmZidgFiTRVlLbuQZzEMR9Ad3eg7l7hG1fcTF2SppLO7a+z0ZgIW4LIn7BxLNobr7MWaxO7CDn5zF8arHbrhV14/6EqQdTv3Xo2RGXnPuw==
    rootUser: AgBiCHVD/N9iD4SuskoioZZ6axeOfNhKdhWBh1rl7RhGUFNKO1gSu+snZ0YBVrSEt+pUs4/k6/HMOC04nGoEqa9JFDPr2he3/1b2PzD6j5lIDZVlhrukBkQtruGIKNBGtIYyyH2E2WpGTEP33TcGBgvEv9Rlcrskdr17RzMRTLYdueUm6eiK4/vken1GLZK4hMeyQ1RY3DD4NsiR66M2wVc3sr7AsgB15bo80n4+F4cEvk+aBTOqEb6XO7WuCNM6Qmi9baAoVMBuPw9SqGkcH9jV2S38uNZD30hwURnXPyPXDWofdhcbQeNSRKQHFHXF/3Qkq2cW+wkT7OXWuXlDbxtPcj2Ou+38S408YLV7W03xDpT7yVAuxoFs75M1XoPpVvvnj+lA05WkTAWH/+SbKDvqshqriE/PA4M+lZCDgUzvTV+heTI5mLxBMbZAtRMLWInbpg6+9m2i+ePyaxZkIaPWZt3NrqDRFSSTt05xdLePLS3tcpYDpSh/4VX+mErc77ILOQqYXar7CYOpQ86IIVo9n2pJlzsbNk/DX3vCcDN7qMGOaZXbAG8tIVvvtc+WhCEgf9AaUVoulll5xX0txd5vV44LwGGCULso71wSZ7Mu/j3lVVqbxJvZHKkaA9LzTUo6QKyaFEMqVjS+LWPSwVIebqRXedKtQLIu0pq3LBD7ItLjuTWc36l0dPZ9+pUuPpVhQfnc
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: minio-system
    type: Opaque
