apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-ingressroute-certificate
  namespace: media
spec:
  secretName: prowlarr-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - prowlarr.kube.eggenberg.io