---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-smb
provisioner: smb.csi.k8s.io
parameters:
  source: //storage.eggenberg.io/media
  csi.storage.k8s.io/provisioner-secret-name: media-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: media-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: default
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino  # required to prevent data corruption