apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseerr-ingressroute-certificate
  namespace: media
spec:
  secretName: jellyseerr-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - jellyseerr.kube.eggenberg.io