global:
  hosts:
    domain: eggenberg.io
    gitlab:
      name: git.eggenberg.io
    registry:
      name: registry.git.eggenberg.io

  nginx-ingress:
    enabled: false

  ingress:
    enabled: false
    tls:
      enabled: true
    secretName: gitlab-certificate-secret
    configureCertmanager: false

  minio:
    enabled: false

  appConfig:
    object_store:
      enabled: true
      connection:
        secret: minio-secrets
        key: connection
    terraformState:
      enabled: true 

gitlab:
  webservice:
    ingress:
      enabled: false

registry:
  enabled: true
  ingress:
    enabled: false

installCertmanager: false

upgradeCheck:
  enabled: false
