global:
  hosts:
    domain: eggenberg.io
    gitlab:
      name: git.eggenberg.io
    registry:
      name: registry.git.eggenberg.io

  registry:
    serviceName: gitlab-registry

  nginx-ingress:
    enabled: false

  ingress:
    enabled: false
    tls:
      enabled: true
    secretName: gitlab-certificate-secret
    configureCertmanager: false

  minio:
    enabled: false

  appConfig:
    object_store:
      enabled: true
      connection:
        secret: minio-secrets
        key: connection
    terraformState:
      enabled: true 

  email:
    display_name: 'GitLab'
    from: 'git@eggenberg.io'
    reply_to: 'noreply@eggenberg.io'

  smtp:
    enabled: true
    address: smtp.protonmail.ch
    port: 587
    authentication: 'plain'
    user_name: 'git@eggenberg.io'
    password:
      secret: smtp-secrets
      key: 'token'
    starttls_auto: true
    tls: false

  shell:
    port: 2222

gitlab:
  webservice:
    ingress:
      enabled: false

  gitlab-shell:
    service:
      type: ClusterIP
      internalPort: 2222

registry:
  enabled: true
  ingress:
    enabled: false

installCertmanager: false

upgradeCheck:
  enabled: false
