---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smtp-secrets
  namespace: gitlab
spec:
  encryptedData:
    token: AgAo1k/9Dk/8R+nzGPC2Hf/LBJ0+9LdD6CJa4zzxkPyiAy5gM15vZ9I2SzK36rNCgptuQBhWq4bLKXK2zHZ719k+hBRGn2o2KKaAL7AiIihhryDW4V6FPXVADcjzJJfdNSja8Y3VuGGRgOBpC+6IiG8lbEmcu8YCpPWes4ZNt0D/kZ+ZXqhGUk30tRUI6/ga9QcjIZNNjt0J3CFkHrre8laipohbC7EJGjmb6TfA65y2nIlUDcRm8SwV9AiHmpp1c3KwJL5G3D6cqnrQsIas/BR/IvZdzvmxmFPbW4bJBXU6PBHQu3gpAWeoBdQpuGeyOXBnSYKCxClwZeQM6Art/d0rL0By3cSeI96qlpbP5v95mkgf2p+Q84liSFzgORutI8MH2z/8Nq884ZXaME0W0UoEz73NkktMewLjzjq/umt1Ze7jZvAMoxeiqAAkaZRKpVTAIw+aE98aXrP8dLBZaPWm3Aq6Z/c7/pETtCqqn+dmc65pG6GUkdqjBDkn6GOLF4ua6oVFE3JZDUwelRXG/EhY3VgCo9BFml4QScxPeJvCD2tROjn7scjiM/fDu4jyJYVHUGU1NAhpHxuV7Du/+Q3W1sViXIPNc1gt+Q/bl8ig8An3ZLMH0BqnyUtaM4UpLlzSdBK1pTvZ0W2Sc+oRuHpMRaQDc6nAe4iNmrVcvrW+iKLAoDqkr28dU2FI3C7D7jC7TmNlluIjOfk8I3ojlFRJ
  template:
    metadata:
      creationTimestamp: null
      name: smtp-secrets
      namespace: gitlab
    type: Opaque
