apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-ingressroute-certificate
  namespace: pihole
spec:
  secretName: pihole-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - pihole.kube.eggenberg.io