replicaCount: 1

DNS1: "1.1.1.1"
DNS2: "1.0.0.1"

extraEnvVars:
  DNSMASQ_LISTENING: "all"

admin:
  enabled: true
  existingSecret: "pihole-secrets"
  passwordKey: "WEBPASSWORD"

serviceDns:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: 10.10.20.53
  annotations:
    kube-vip.io/loadbalancerIPs: 10.10.20.53
  externalTrafficPolicy: Local

serviceWeb:
  enabled: true
  type: ClusterIP

persistentVolumeClaim:
  enabled: true
  storageClass: "longhorn-daily-backup"
  accessModes:
    - ReadWriteOnce
  size: 10Gi