---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secrets
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgCKDItNWSNOjUlss/uApQYzjYdJNFbdDLgeULi1R4k0ynbwOoK+sHodymCUer+qAm/msp4Dc2LRmc4I9aRSSD0NApoNie3WrQktVLfmB31bBBYXxKdf7vqTHWuID+ZLs90i6vXlOYiN2VPs0UXTzur782ecTeZZGriSFTFcnqaLhuemyUBMNOCdKg+xHOrMjYLCSrGaNZE06UwZOkDNajn5q4/JW9HwJfCVEtLXJuZEFVZdIopwLsQ+mVckJmKWkRUoRC0TQ5p7LQUMH/KoNMYFVwlKyzIxcwUrkgtCT9h5qCeOVOnEfS7cpfZNjvmqsQI3tJdhTz6emHh/JsEvkkbt7F3+QRHYazj3UzZn3y6YwtQwn6YJy4WdQBHYXNuloluzylu9CEFLxu4dcjcAXbXx5SGwGv3Xqs2VVaYV72mYsPjmYnQyG5toQ/zGO/BLLrX3NQa11cs0D390Fu9ln69drfTHJmuAdSikeTKPjXMISVkDvzXyTSaVI8J7c65xhhcgwRPg1M4Hqc1AiUxC9vp42PQhWl8qHS+0SzlH7qk9h8g4uU23gzeR0niObd7Wh51mwrLUknJwur7URSV9e8KMHVgbbOEwfaczChSw4z912OWPlahCsny+uWnqItfYNa4isbwTPKUumeCkO+HIBwT1/slz5TewjT+A5gq9RJI+BgccFm9KIatsOIIXYa91BzfuOM0KzZoqh6iZ7wB6/ctTrUF0lJzDckzweA85WPdy1Ifu
  template:
    metadata:
      name: pihole-secrets
      namespace: pihole
    type: Opaque
