---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secrets
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgAVkqrsn8HYomeX6I7q0hIXtC4DrxV/47NTAa78XHLZwkKXVhIKqWt47xLRi+laul6G0n3+OwX+0HA2fal2+Btdu/Cwn7TOMuNSGZSC/wZPOHi353gf66N0jscDzrbt6hGIZbXH9cQIY3frBg7iM1P9VeA8/pFZDQ0uSrdu8jECVoefTl2k+2gcpkUoprsnvcHhCZUQh6UEpPwVEwR67R70WnVGDXJhQHoCM1TrmqUU1uPjwruBqAbyXcguqx/CtlM7D8RWXcdAfKOy9sloYv7J6hGNw0zpaD89symz5pHVbkqgsa92kDiBaIDv46J0fgAE9vaXcqKNbK4u/93ts6N4aFAH1L5O1IBYSH5GVIc29lryyJustD0KcSyDpjcAJHFE+rIhqkiZrecSZswlP7KOeXBdMlc8PyUatMhnjK58NbEwVEsxOO4aPq/cftonYRx0Us4JtpiV6PeSp1QU8C8POrpm9dkJ4+p4h5UqI/Dzy6PmEqylVNQHLzk4KCDKvX/yGL1CBM7m4MzFD3l5tHwaqIQdZy7evDHvthklJ579yrtuq3FhplU9LbPIZ+rTsdlltqIgAIsXg+8UVTZeSIBvc8oo/xGl3Qr+I0coj+qt5lx3VHAs84A2Zv6BV/ss1PySM7HhQw38WVGUZTZwc6nGFXlaLO4OIbTJZpth1MVNdqduUoBgeT5EEVOLPziry7dyravK2T8o/ehffIspLaQH6qXvrvO2AgZHSg8HtKcWPw==
  template:
    metadata:
      name: pihole-secrets
      namespace: pihole
    type: Opaque
