---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secrets
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgALofCDD3LpfYDOjU6SEwiGgxuE7DvIgH+O6Mz3LJSJNjXvEOOWu9EU1GwhO9Pgtv03TbdZFm6RE82fPwQy3xQiHD7Dk/lVmpnb7vLjX30wwa86EF+2jXFGEW0paywXVVzeotobHVbZ6qNhxwqWI7W6lNbSs0pbMuAL7ddz1NdipPyTLJUYQAXAYhjHsD1bHfxnfcU792YYkTtnnA256S2UfIt9Jq/fbrfoQCHV5v9JCRqybf8Q9w22gK+qUMxQQ1iEqh3ymoWVOFzHXZCuX9SgsGSxn2j0AKcuyu/F4i+pqt1ZnpFAizJZMXdmkiCwT8G8r6gdJ1IZ8KyInohr9nrpRgLgEEswe0OGOaucwQA1PK0ltkOrDrD+Aj3o4N/v5lJUMaDIpNt6GhrRjKaR/fGyfUVFwCIPcwwoI9AqHqjo1uk0CcBHI/D+JKclNdMJdJKsmhbEV3ZYzvDArR9kXQHNF1D8hizQo5RjDAzOOahpRpKGsDXIsinBPcyhm5lBUYwuI41nBOC37/cNx+iQrQFfDy7zsDKFa/qvWdW1yFtJNh9fGFO6C64On+OCTFmbJc68hFG0Wy4ndzL8pndBuOPMVEUphbOXsmURzd4++w6BGjDp/1rZlPxxT7EQaIEKBON6qu/1Kk3LGp9YZorgUvpOCSYFYb6doqAw6CdLax2zspwuplnziXhNprzBqRhpwT3V6RuDWAuMAfB5cdNFGK+i50vgEImx2DWop/qBQ+wt/egHXbvAilVVf78IORnjRD0a9g==
  template:
    metadata:
      name: pihole-secrets
      namespace: pihole
    type: Opaque
