nut:
    password: ENC[AES256_GCM,data:9iVsGB6h+k2HE1qVP5EHSTWx9pHn2jQYOzgtMAGHsEA=,iv:KtmOGpSSs8ygrQo075TOTfZGVgbe7cbFXt0T4njnRWY=,tag:lwuHcwAtp0J0hxD2HwWexQ==,type:str]
sops:
    age:
        - recipient: age1hlkhznl99sc8kh33weq7z90xdrsqz85wu5c86x7kf5pkxqvum3pq2n4d7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNzdsUmVXQVVGNHQ3dGRa
            TmFWc1RvMEZpa3ZYRVZrYnppU2Vaa0pyM0RnCk8wMkFUQTV2R0RUWDVXNEVmaGYy
            U1B3K1ZXV2NrMG81cHZGQytYSVhJR0kKLS0tIHpmZlJYblprOXNJRUFzS3dvY1dL
            MklOT0VMSkd2WW94K0pNSmp3NHJraUEKf9gSZ9i6pQHscKDYIy2+fxpE+AHHErjC
            hwbl1bZwcguV9NcaaiBG3U4wn8HUmMz1c1Z8CgtDfgQ5nH6Es3607g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age126w8nwakc83s35znk5av82nljfa63m7v7kvwljxanjdn5d9eeqnqm7vyhs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZXNpTnNMcDNpZjg3T3dy
            dUxiVmtCSTRDaWsvZEJnS0xrZjN1eWNTK3dnCmJDbXRUZFRJQ0RkeCtjNEU1S2cx
            UGZXbGR4cVVjbzlRM2QvYklqVnMyNFUKLS0tIHNzQitRTnlSM1RseXRFZmZFY1Av
            NHIxTDR5OGpDcWhxaThJSE9PTmM0L1UKseysxYhezzr8WjQbe4R6SzsqHiE17aJZ
            34UZ97Lj4ZJTN7o8ogtbdmNs9hdo5VHQteUyheiyrPYIMYMuNzffSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T15:58:27Z"
    mac: ENC[AES256_GCM,data:JBEEyQstMavrdaIjqaEvxqfG5pWnyKIFfgaJn02TIx5M/swaOUhFIqeQFlXQ0ZTR737cniudbx9BXxhHAZyaVsWWmlAKFHRtnOL+6rtY52JTjkVfAkOhnjIYS5so0ukvrHPzhL+9COZzOL7RH7s0dqMWHVrvn6mffr5EZze8ZOw=,iv:QxeSBtS/2/WSv7RNkFJvDfxe3rMp9LbqsW47TSj4iuM=,tag:CiPbEdbWFbX/OrWR+IK8Rw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
