services:
  wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: always
    networks:
      - frontend
    expose:
      - "8080"
      - "2022"
      - "443"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"

      - "/etc/pterodactyl/:/etc/pterodactyl/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
    labels:
      traefik.enable: true
      traefik.http.routers.gameserver-plg-https.tls: true
      traefik.http.routers.gameserver-plg-https.tls.certresolver: cloudflare
      traefik.http.routers.gameserver-plg-https.entrypoints: websecure
      traefik.http.routers.gameserver-plg-https.rule: Host(`gameserver.srv-plg-1.eggenberg.io`)
networks:
  frontend:
    external: true