services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.6.1
    restart: always
    networks:
      - wings0
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"

      - "/apps/pterodactyl/etc:/etc/pterodactyl/"
      - "/apps/pterodactyl/lib/:/var/lib/pterodactyl/"
      - "/apps/pterodactyl/log/:/var/log/pterodactyl/"
      - "/apps/pterodactyl/temp/:/tmp/pterodactyl/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"
    labels:
      traefik.enable: true
      traefik.http.routers.gameserver-plg-https.tls: true
      traefik.http.routers.gameserver-plg-https.tls.certresolver: cloudflare
      traefik.http.routers.gameserver-plg-https.entrypoints: websecure
      traefik.http.routers.gameserver-plg-https.rule: Host(`gameserver.srv-plg-1.eggenberg.io`)
networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0