apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: huntarr-ingressroute-certificate
  namespace: media
spec:
  secretName: huntarr-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - huntarr.kube.eggenberg.io