apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      name: web
      port: 80
    - targetPort: websecure
      name: websecure
      port: 443
  selector:
    app: traefik