apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pterodactyl-ingressroute-certificate
spec:
  secretName: pterodactyl-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - pterodactyl.eggenberg.io