kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-panel
  longhorn.io/recurring-job-selector: |
      [{ 
        "group": "longhorn-daily-backup",
        "isGroup": true 
      }]
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-database
  longhorn.io/recurring-job-selector: |
      [{ 
        "group": "longhorn-daily-backup",
        "isGroup": true 
      }]
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi