kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-panel
  labels:
    longhorn.io/application: pterodactyl-panel
spec:
  storageClassName: longhorn-daily-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-database
  labels:
    longhorn.io/application: pterodactyl-database
spec:
  storageClassName: longhorn-daily-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi