apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'homelab-{{.cluster}}'
    spec:
      project: default
      syncPolicy:
        automated: {}
      source:
        repoURL: https://github.com/LucaEggenberg/HomeLab
        targetRevision: HEAD
        path: argocd/applications
      destination:
        server: '{{.url}}'
        namespace: argocd