apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.17.2
    helm:
      valueFiles:
        - $values/services/cert-manager/cert-manager-helm-values.yml
  - path: services/cert-manager
    repoURL: https://github.com/LucaEggenberg/HomeLab
    targetRevision: HEAD
    ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
