apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-certificate-secret
  namespace: authentik
spec:
  secretName: authentik-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - auth.eggenberg.io