global:
  envFrom:
    - secretRef:
        name: authentik-secrets
    - secretRef:
        name: smtp-secrets

authentik:
  secret_key: ""
  error_reporting:
    enabled: false
  allowed_hosts:
    - "auth.eggenberg.io"
  email:
    host: "smtp.protonmail.ch"
    port: 587
    use_tls: true
    from: "admin@eggenberg.io"

postgresql:
  enabled: true
  auth:
    existingSecret: "authentik-secrets"
    secretKeys:
      adminPasswordKey: "AUTHENTIK_POSTGRESQL__PASSWORD"
      userPasswordKey: "AUTHENTIK_POSTGRESQL__PASSWORD"

redis:
  enabled: true

server:
  ingress:
    enabled: false
  gateway:
    enabled: false
  service:
    type: ClusterIP

outposts:
  docker_image_base: "ghcr.io/goauthentik/outpost"
