---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgA0iUSPGROhbMJVXIw8Kpjkx5TVRIV00eR0Y8Ebf2EgCU30Z9SEwKRqS5ihVnVbMbhaLxj8E+5DujI8GrpS72T+Kl0amILOSlnyt1QVa1KwKmZK+6A3N/HdJQW2eEXG14MMqWWCpobWbTPmTOhIiAKVVdHydFENE5v3x6v9yLXGBioAQATdQra/RV1gYcK2rUgveZhOWiEla+5bOakDz+2IAwtfjwASo78zHWb6KTivbKwxAPq21yC2FjtNnj/F6J/DQFuz0n9oGi08o/WeIQdmVfa+j0grwJVOq1zGDC8mu8s/1w1wI3GHFTGlylGg/kEWN/fwpYGvx8fIqtkcsw2TpK7uFH25L61at8jmxFqAZ60p3bkAckrA5I3tn8Ei74I8ykQNy9dXN5N8jcaDlZPALaE3BBTIx7fSmusyx5uDWQFRVKYdIzG4pqdiHPgPPi/gSj8/mB3YFrIo21q0V9kI59GZtoSk1JCAFvzfi4lfR/K8wLcgZMrNHgSFGzoX2FHmMe7A6lTFBT5bODeiRCyPaLeWH4FxE3k5d9Q9kKFlYQiC9GZig21KRA7s0T3E5vq1IgNOHKzFE8sxdNAL7+QWPM2DDK8BPaO/9rh2w0LUdslYUroTHgUMO6FKDRL/HEOACYBbtp70p+XVNhY5hY4gdxYIQM8VO6BLgWzCqgXrZILm+UOl/FaLDQyw+oCSUnTl35lgCsPhzM5HvYsIVkf+Ii6JF5jaKSd+A2IL/HE3zQ==
    AUTHENTIK_SECRET_KEY: AgCQx3PoHwN+iOR9KabY+H8KZstqFa9wcR68WePDAtiQNkpBfYIsGEzl5EloPojzxOLOkvvLYMNe/NpYO89x80pnZUSv7RWRVw2H5vyOPatZa0yeTUTA8AYFaENHyIajYgsmxx8anO001x81NrRBpu7EHnYPhd8sk6kNO+ju6nxNAvnXpY6MBqqGXUEFwmCUdu6/Xgpx2XRn+ZMPipVTtfN8YiDfX4SYiyD66t1QaOdwi0lrmqDwOSqxgwL0ez2ba/DrPezsO6emI3Wk6ZJHcEhytZ3bPkdsMV3A/OJYJ0BMZ5RmzUbed/e9H/nrpaho6NHfaHPQPCwlNrW26sAhzXGiO/iNUTaRM6ZjUxjTCXcnB3xKTMYzfLRSxXXGepzuYM3rRy9J0976vKkXiP1YG8H/pzTnuSF2rXgMuAUd+bS4lWA+qaq/vuq0vmwSFGfwYFygU0+/M1bMJ4J13/O6CXzB9RvVIXiNj4sd3K4RBDdoJI1WbtqdyK9FvioFuCeu/L6ic42uyvjMAVD8tJYCX2YXDdxQ3MbtypDRVN4Y8HGQl2Y/1TkFRKp0+eAR3/DTwVSSfhjdkrzpwUxHEmFmgeUwzNNJHismIglsTUAGHccAGDGmhNHwzUmEO90MAtrtz1lUJ1zln+6zOouX87aKoEAFI7dDPDvWPVTHH4Yz0u6bYeMu8fXptHX/eV+31xCbHOmW6rRx/qbFzEoDEZ/bQbUewZ5nAgdq303QVVX9aaX2VA==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
