---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_EMAIL__PASSWORD: AgApAIM9kU8fQltcgMnuYgiLaBWluxVZGChjff4wWLfWztA4exQ9OKHW0eYm1vH5/koLnMELmR3uRzWwCNA+ixuINEoCKWyJ/5SHKmse4CWjXQWmyWsVcx/7V2M799L1B5HMKEPNldWG7rUrVNC0418Lc8bTQhYcqHDJZSDKiQaTUlS9tT+Ut/Q+DdZRcBqXsJKpO/32VEcC5p8EyhlAQiNSgbbtW0qdaMocTkI186qDcKGRSy4/InKY/dVsh4kQfH3wP/Z+AK2NYG4fgo0C7DNlLc1uJw1SdMeBs2CQZ+aiaclqelriWQaM78xoFtEYr69CwWwyo48dGlKYn7Z2WPvdac8huqI75PVHwTaaQDtZfeIoDEyzGrw4/V+RLtMc+Vx04inlY5koXeRDJ45D7naycVw4vAVLMnZgiT4ibpjx9ZR9UYJMLxK9EQybNS+ZbWv8UGpZ/kSDMAWdaOKZrHP3C40vTec+bFCWzB0JHDoCc0i/EKjOrhkAanrmqkxfl6qYvzf70rx8+c8kpY9wGIALhEBn0AxwTFO3eV93tqf52B0wl10uYO0Hbov8CZbYcY31Nr/yIIK3Y+Qsgmw3RluCvlgOyrnby5Xu5yEFIZXIAHy0z4n1s1V4o0R87SKzKJobDtDbk08kRECqgscTvAaApRYx+3zyHhDf7DQH9em8ZTomZMiMW0SC6xGOZWKpxDB9nZvQxsj8W5skPceWPgW6
    AUTHENTIK_EMAIL__USERNAME: AgCy6DMWreO0IVeYTqIh3li+7RSQ6awgVenaScBQO4JC0uGlDMIhknbPaC7O4XDOdAdIBvuQTPFljcavMtb460FsWG9xVse0UqkpR34JqPKM+tiTvR2BLwEKDCbo++ouXKc7Wy6zisnnm1mS2zuUJAm+VfPrKTpb8YX8U6Vdym5rgURQGhyiUWpXklo0d7dVZPMQCu4MDgPnUOFyXxekLdlxajRVGA1gSZVU4HTW8ZuY8cHUFmVw1X2pNN2xMxmKsL2suWmzMxz8u/NAQ+O4oyf8DWmcq0Zqw7KmPHnk8mJ1tr47360E7Y3sxhVt8aUDAatpRKjuKBJMQqHB/0IkmftNP9KTj4DhU2a1qQ6ESnHnCflIU9mOaZPbYsl70irrTyZoKVpty5Nr3SpNp1BJ/I530Eha8w/Md9wk4K8njcwK5czicB4M6m3OFDOFCOrEU6QHykAG/oO2oX8Vidn9a+8Nwrdyu8mjBJQnHdjR/xBXOgj8+6xqhUEJhdrA+VuzCS2tM7xQJpTHEiky5TvZqOimJmLHamRBK4bTFDZxfup42eD5YR8jETefU2FUW/Rn5PLFQ+6Il2gBF19ojkyfE7J0A0IwkAr42wiFqFEodmQQKgsQvVrX6jC2tkMYKKV1dsDZQj+4CmsEhbLdKiOpcCama49aue5kr4zlQS1EjKY9vG31Uw2fVAyg1zsym9LzQNWfCvR3ctIBGfJmeWT5HHFVcAg=
  template:
    metadata:
      name: smtp-secrets
      namespace: authentik
