---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-smb-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: jellyfin-smb-pv
  storageClassName: smb