apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-ingressroute-certificate
spec:
  secretName: mealie-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - mealie.eggenberg.io