id: ssh-deploy
namespace: provisioning

inputs:
  - id: user-name
    type: STRING
    required: true
    defaults:
      - "ansible"
  - id: ssh-key
    type: FILE
    required: false
    description: "public key"

variables:
  ansible-playbook: automation/ansible/playbooks/ssh-deploy.yml
  hosts: ubuntu_servers

tasks:
  id: deploy-ssh-key
  type: io.kestra.plugin.core.flow.WorkingDirectory
  inputFiles:
    id_rsa: "{{ secret('ANSIBLE_SSH_KEY') }}"
  tasks:
    - id: git-clone
      type: io.kestra.plugin.git.Clone
      url: "{{ globals['github-repo'] }}"
      directory: automation/ansible
      branch: main
    
    - id: ansible-playbook 
      type: io.kestra.plugin.ansible.cli.AnsibleCLI
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
        image: docker.io/cytopia/ansible:latest-tools
      env:
        "ANSIBLE_HOST_KEY_CHECKING": "False"
        "ANSIBLE_REMOTE_USER": "ansible"
      commands:
        - ansible-playbook - i automation/ansible/inventory --key-file id_rsa "{{ vars.ansible-playbook }}" --extra-vars "hosts={{ vars.hosts }} user_name={{ inputs.user-name }} ssh_key={{ inputs.ssh-key }}"


