apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flaresolverr-ingressroute-certificate
  namespace: media
spec:
  secretName: flaresolverr-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - flaresolverr.kube.eggenberg.io