apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cleanuparr-ingressroute-certificate
  namespace: media
spec:
  secretName: cleanuparr-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - cleanuparr.kube.eggenberg.io