apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
spec:
  project: default
  sources:
  - repoURL: https://charts.goauthentik.io
    targetRevision: 2026.2.0
    chart: authentik
    helm:
      valueFiles:
        - $values/applications/kubernetes/authentik/helm-values.yml
  - path: applications/kubernetes/authentik
    repoURL: https://git.eggenberg.io/luca/homelab.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
