apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.17.2
      helm:
        valueFiles:
          - $values/applications/kubernetes/cert-manager/helm-values.yml
      chart: cert-manager
    - repoURL: https://github.com/LucaEggenberg/homelab
      path: applications/kubernetes/cert-manager
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
