apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver
spec:
  project: default
  sources:
  - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    targetRevision: v1.17.0
    chart: csi-driver-smb
  - path: applications/kubernetes/csi
    repoURL: https://git.eggenberg.io/luca/homelab
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system