apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
spec:
  project: default
  source:
    repoURL: https://git.eggenberg.io/luca/homelab
    path: applications/kubernetes/homepage
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated: {}
    syncOptions:
      - Replace=true
      - CreateNamespace=true