apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.11.0
    helm:
      valueFiles:
        - $values/applications/kubernetes/longhorn/helm-values.yml
  - path: applications/kubernetes/longhorn
    repoURL: https://git.eggenberg.io/luca/homelab.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
