apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie
spec:
  project: default
  source:
    repoURL: https://github.com/LucaEggenberg/homelab
    path: applications/kubernetes/mealie
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: mealie
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true