apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
spec:
  project: default
  source:
    repoURL: https://github.com/LucaEggenberg/homelab
    path: applications/kubernetes/media
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

