apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  project: default
  sources:
  - repoURL: https://charts.min.io
    targetRevision: 5.4.0
    chart: minio
    helm:
      valueFiles:
        - $values/applications/kubernetes/minio/helm-values.yml
  - path: applications/kubernetes/minio
    repoURL: https://git.eggenberg.io/luca/homelab.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
