apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.18.1
    helm:
      valueFiles:
        - $values/applications/kubernetes/sealed-secrets/helm-values.yml
  - path: applications/kubernetes/sealed-secrets/
    repoURL: https://git.eggenberg.io/luca/homelab.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
