apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
spec:
  project: default
  sources:
  - repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
    chart: stirling-pdf-chart
    targetRevision: 2.2.0
    helm:
      valueFiles:
        - $values/applications/kubernetes/stirling-pdf/helm-values.yml
  - path: applications/kubernetes/stirling-pdf
    repoURL: https://git.eggenberg.io/luca/homelab.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: stirling-pdf
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
