apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingressroute
  namespace: argocd
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`argocd.kube.eggenberg.io`)
    kind: Rule
    services:
    - name: argocd-server
      port: 443
  tls:
    secretName: argocd-certificate-secret