apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingressroute
  namespace: longhorn-system
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`longhorn.eggenberg.io`)
    kind: Rule
    services:
    - name: longhorn
      port: 80
  tls:
    secretName: longhorn-certificate-secret