apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-ingressroute-certificate
  namespace: jellyfin
spec:
  secretName: radarr-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - radarr.kube.eggenberg.io