- hosts: "{{ hosts }}"
  become: yes
  vars:
    user_name: ansible
    ssh_key: "{{ lookup('file', '../ansible.pub') }}"
  tasks:
    - name: create service-user for ansible
      user:
        name: "{{ user_name }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
    
    - name: check .ssh dir
      file:
        path: "/home/{{ user_name }}/.ssh"
        state: directory
        mode '0700'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: add public key
      authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ ssh_key }}"
        path: "/home/{{ user_name }}/.ssh/authorized_keys"