- hosts: "{{ target_hosts }}"  
  become: true
  tasks:
    - name: upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - meta: end_host
      when: not reboot_required.stat.exists

    # TODO: how to handle reboots?