apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant-ingressroute
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`*.srv-plg-1.eggenberg.io`)
    kind: Rule
    services:
    - name: srv-plg-1
      port: 443
