kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyseerr-pvc
  annotations:
    longhorn.io/recurring-job-selector: |
      [{ 
        "group": "longhorn-daily-backup",
        "isGroup": true 
      }]
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-pvc
  longhorn.io/recurring-job-selector: |
      [{ 
        "group": "longhorn-weekly-backup",
        "isGroup": true 
      }]
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-pvc
  longhorn.io/recurring-job-selector: |
      [{ 
        "group": "longhorn-daily-backup",
        "isGroup": true 
      }]
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-pvc
  longhorn.io/recurring-job-selector: |
      [{ 
        "group": "longhorn-weekly-backup",
        "isGroup": true 
      }]
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-pvc
  longhorn.io/recurring-job-selector: |
      [{ 
        "group": "longhorn-weekly-backup",
        "isGroup": true 
      }]
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gluetun-pvc
  longhorn.io/recurring-job-selector: |
      [{ 
        "group": "longhorn-daily-backup",
        "isGroup": true 
      }]
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
--- 