kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyseerr-pvc
  labels:
    longhorn.io/application: jellyseerr
spec:
  storageClassName: longhorn-daily-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-pvc
  labels:
    longhorn.io/application: prowlarr
spec:
  storageClassName: longhorn-weekly-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-pvc
  labels:
    longhorn.io/application: qbittorrent
spec:
  storageClassName: longhorn-weekly-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-pvc
  labels:
    longhorn.io/application: radarr
spec:
  storageClassName: longhorn-daily-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-pvc
  labels:
    longhorn.io/application: sonarr
spec:
  storageClassName: longhorn-daily-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gluetun-pvc
  labels:
    longhorn.io/application: gluetun
spec:
  storageClassName: longhorn-daily-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
--- 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: huntarr-pvc
  labels:
    longhorn.io/application: huntarr
spec:
  storageClassName: longhorn-daily-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
--- 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cleanuparr-pvc
  labels:
    longhorn.io/application: cleanuparr
spec:
  storageClassName: longhorn-daily-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---