stages:
  - validate
  - plan
  - apply

variables:
  TOFU_VERSION: "1.10.6"

default:
  image:
    name: ghcr.io/opentofu/opentofu:${TOFU_VERSION}
    entrypoint: [""]
  before_script:
    - cd infrastructure
    - tofu --version

opentofu-validate:
  stage: validate
  script:
    - tofu init -input=false
    - tofu validate
  rules:
    - when: always

opentofu-plan:
  stage: plan
  script:
    - tofu init -input=false
    - tofu plan -out=tfplan
  artifacts:
    paths:
      - infrastructure/tfplan
  rules:
    - when: on_success

opentofu-apply:
  stage: apply
  script:
    - tofu init -input=false
    - tofu apply -auto-approve tfplan
  needs: ["opentofu-plan"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
