stages:
  - plan
  - apply

variables:
  TOFU_VERSION: "1.10.6"

default:
  image:
    name: ghcr.io/opentofu/opentofu:${TOFU_VERSION}
    entrypoint: [""]
  tags: [ "internal" ]
  before_script:
    - cd infrastructure
    - tofu --version
opentofu-plan:
  stage: plan
  script:
    - tofu init -input=false
    - tofu plan -detailed-exitcode -out=tfplan.prod

opentofu-apply:
  stage: apply
  environment:
    name: prod
  script:
    - tofu init -input=false
    - tofu apply -auto-approve tfplan.prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
