apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver
spec:
  project: default
  source:
    repoURL: >-
      https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    targetRevision: v1.17.0
    chart: csi-driver-smb
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system