apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
spec:
  project: default
  source:
    repoURL: https://github.com/LucaEggenberg/HomeLab
    path: kubernetes/services/jellyfin
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

