k3s:
    token: ENC[AES256_GCM,data:aKzXH+lt6lW1ilPEZHq67dTrdNO6Q9AiWM736W4CS6CVI5gWSj73YHwA/1uHPHZoRTnWV39U4ZX/FPwvN4T6mbNjKSUvALb20pcekeVakUxdMzA2tkSxvPvJNV5ssfpVjEXbr8K4qECG3+QR,iv:ckBYEq/BL+wLEd7rB7u8MwlzwAWM0UEtn1q1o3qTP3o=,tag:ItoMa5JNOgJfrMLyhvPjmA==,type:str]
sops:
    age:
        - recipient: age1hlkhznl99sc8kh33weq7z90xdrsqz85wu5c86x7kf5pkxqvum3pq2n4d7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRDNncmJ0dGZmTWJYZWRV
            RmFhZVRnUm56WERmMUFDaC81bCt3ZE9HL0VRCjRmTU1mM0tuRGQ0UXI5aCtJcERz
            ZjdhU0JpUWwzYWdxUy9lR3dYYWFCNVEKLS0tIHc0R3R1UTc1dFpBaEsrMHVwVlo4
            M1BrVVNxbnlzRnNMNXZMbzFIL25VMncKE2F2E+Dht7BD8Lskds4na5jAEXm03Ep3
            Ehq1TNu1VG2A0pbO5nq75BBAFhlr88TtAlpi4FGuronWUGWLNwIGhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zf6eg0y2d99r8j7yy573almastw7he3qfke5df7t0rkmmysz956qg0p607
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbERoZnJOeUoxUWhwNnNq
            bmNlbkc2YUd6OC9MSERLSWZFT21SajU1ZkNvCksrODZsSUlqWGhqdEdwZldRdGV5
            NXdGTGNyZ1AvYm5McytIRHdEQlg2REEKLS0tIGVRZTJZeERpdW1yS2NVM2paMURX
            NlZQQWdVZEJJUW9lQ09tV2VBdkNPODgK9dmieEMoMpqz/RvapjDti1hExffToO50
            wXdOZyESfML3dwSEXxsFaAS6Ksnlr0SE7g5wOndLezLs9L74beLXvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qql9ema67rruk8mgl9mcnm6dd274w4r5jzxv05av8ut9zdmx0p2q706rrh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y2ExMmJOMXhjZ2RnNVFT
            VVk1VGcybndJSlNGMEtXR2h0ak51ZDEwTHlJCkhtQXhQZjQ1UEdwdnhqNXc5NjMy
            akRONkJSTWRkQ0NzUWU0R0tFMXJQajQKLS0tIGNieHVNMWpnbEtkeUF0YW9Nb09O
            VEhFaHNSMUZ1MHFsU2pZQ2ZzeVkxaVUKLS1ZX/K1D8lfG2Lv2kwDLEqwTSUbS9gM
            1U3JSK/5mYlBbeKbVKGoadJKgKKiU8a7+wZAbJSsEGfcaKe7BZpp7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16rllrwvq0kg4yz9ur4vgjc5tn3rs0a7p0rcm8dmqk26etc7uvggs7uay5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VVdkNENlbG1JRlQ1TlJm
            S2JIbTNJbG1RVEI3Z0EvUUVsb3cvWVMvSGhjCjVSU2d5VFZHOFFzUzVGRXI3RXdG
            L0N4K0J3MWJ2NGZEVUJJUzl4Q3FpMUkKLS0tIG5FeWRLSDhZd200ei9INWhiclFj
            Mkxma0VwN21pZGs0UWNHUmhhUk5oTjgKGr61vXvSeJKmbaITIGHM9ZeTt/J7LHxj
            sMODRqtVb0Rk0Iro+fRMrEvdQdifects+CAfLsduqTkc/JycJvt33A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-20T13:39:11Z"
    mac: ENC[AES256_GCM,data:9MKORaYCqLH+IDSksceWyQ+lluTLtm28R/FkI89lS1BhYyFu/4w6yS5ITRau2JicjrFcK+l95qnd+5sQ8A8k/CQREolu6M4ExoMVPSAZyxJupKuyfKrQ+LwC4Xn4TUkJsSsHeKFXrYDckpqQlyRWnVhHq7mWwlMgBk1iGT1V02M=,iv:h9umazpBK8aeKD5YxKv02ZprsbOKcupXUtQ2a4d26XA=,tag:XP6bHcQXDM9Kx52H6ql4lg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
