name: Kestra CI/CD
on: workflow_dispatch
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

env:
  server_url: https://kestra.kube.eggenberg.io

jobs:
  validate:
    runs-on: self-hosted
    name: Kestra validate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate all flows
        uses: kestra-io/validate-action@develop
        with:
          directory: ./automation/kestra
          resource: flow
          server: ${{ env.server_url }}
  
  deploy:
    runs-on: self-hosted
    name: Kestra deploy
    needs: [ validate ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy deployments-flows
        uses: kestra-io/deploy-action@master
        if:  ${{ hashFiles('./automation/kestra/deployments') != '' }}
        with:
          namespace: deployments
          directory: ./automation/kestra/deployments
          resource: flow
          server: ${{ env.server_url }}
      
      - name: Deploy maintenance-flows
        uses: kestra-io/deploy-action@master
        if:  ${{ hashFiles('./automation/kestra/maintenance') != '' }}
        with:
          namespace: maintenance
          directory: ./automation/kestra/maintenance
          resource: flow
          server: ${{ env.server_url }}

      - name: Deploy provisioning-flows
        uses: kestra-io/deploy-action@master
        if:  ${{ hashFiles('./automation/kestra/provisioning') != '' }}
        with:
          namespace: provisioning
          directory: ./automation/kestra/provisioning
          resource: flow
          server: ${{ env.server_url }}
