name: Deploy Playground Infrastructure
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      # - name: Set up Docker Compose
      #   uses: docker/setup-buildx-action@v3
  
      - name: get services
        id: get_services
        run: |
          SERVICES=$(find services -type d -exec test -f '{}/docker-compose.yml \; -print')
          echo $SERVICES

