id: ubuntu-apt-update
namespace: maintenance

variables:
  playbook: automation/ansible/playbooks/ubuntu-upgrade-aptpackages.yml
  hosts: ubuntu_servers

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 4 * 1 *"

tasks:
- id: ansible-job
  type: io.kestra.plugin.core.flow.WorkingDirectory
  inputFiles:
    id_rsa: "{{ secret('ANSIBLE_SSH_KEY') }}"
  tasks:
    - id: git-clone
      type: io.kestra.plugin.git.Clone
      url: "{{ globals['github-repo'] }}"
      directory: git
      branch: main
    
    - id: ansible-playbook 
      type: io.kestra.plugin.ansible.cli.AnsibleCLI
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
        image: docker.io/cytopia/ansible:latest-tools
      commands:
        - >
          ansible-playbook 
          -i git/automation/ansible/inventory/hosts.ini
          --key-file id_rsa 
          --extra-vars "hosts={{ vars.hosts }}" 
          "git/{{ vars.playbook }}"
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        ANSIBLE_REMOTE_USER: "ansible"
